##########
# URL VARIABLES
##########
url: https://mruajeje.github.io
baseurl: /Cabari
source-code: https://github.com/mruajeje/Cabari

##########
# SITE SETTINGS
##########
title: "CABARI"
tagline: "Tu librería de confianza"
description: "Biblioteca virtual enfocada en la literatura popular y el desarrollo personal."
author: "María Rives Puertas, Lucía Castaño Serrano, Pablo Barrera Mora"

##########
# COLLECTION SETTINGS
##########
# IMPORTANTE: Si tu archivo en la carpeta _data se llama metadata.csv, pon 'metadata'.
# Si se llama metadata-template.csv, deja 'metadata-template'.
metadata: metadata

##########
# BUILD SETTINGS 
##########
encoding: "utf-8"
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
sass:
  style: compressed

##########
# FEATURED CONTENT
# Solo ponemos 4 para que el carrusel de inicio no explote
##########
featured-content:
  - coll001
  - coll002
  - coll003
  - coll004

# Añadimos la línea para que reconozca tu diseño de 5 columnas si creas el archivo
custom-css: assets/css/custom.css