##########
# URL VARIABLES
##########
url: "https://mruajeje.github.io"
baseurl: "/Cabari"
source-code: https://github.com/mruajeje/Cabari

##########
# SITE SETTINGS
##########
title: "CABARI"
tagline: "Tu librería de confi"
description: "Biblioteca virtual enfocada en la literatura popular y el desarrollo personal."
author: "María Rives Puertas, Lucía Castaño Serrano, Pablo Barrera Mora"

##########
# COLLECTION SETTINGS
##########

metadata: metadata

##########
# BUILD SETTINGS 
##########
encoding: "utf-8"
exclude: [_data, docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
sass:
  style: compressed

##########
# FEATURED CONTENT
##########
featured-content:
  - coll001
  - coll002
  - coll003
  - coll004
  - coll005
  - coll006
  - coll007
  - coll008
  - coll009
  - coll010
  - coll011
  - coll012
  - coll013
  - coll014
  - coll015
  - coll016
  - coll017
  - coll018
  - coll019
  - coll020
  - coll021
  - coll022
  - coll023
  - coll024
  - coll025
  - coll026
  - coll027
  - coll028
  - coll029
  - coll030
  - coll031
  - coll032
  - coll033
  - coll034
  - coll035
  - coll036
  - coll037
  - coll038
  - coll039
  - coll040

custom-css: assets/css/custom.css